# Generated by Django 4.0.4 on 2022-05-25 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_pscat_likes_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='update_on',
        ),
    ]
