# Generated by Django 3.2 on 2022-06-06 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_room_description_room_slug_alter_room_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reaction',
            name='like',
        ),
        migrations.AddField(
            model_name='reaction',
            name='pst',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.post'),
            preserve_default=False,
        ),
    ]
