# Generated by Django 4.0.4 on 2022-04-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='subsscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Package', models.CharField(max_length=25)),
                ('price', models.IntegerField()),
                ('Duration', models.IntegerField()),
                ('offer', models.IntegerField()),
            ],
        ),
    ]
