# Generated by Django 4.0.4 on 2022-05-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='pscat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_head', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('bimage', models.ImageField(null=True, upload_to='pscatimg')),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
