# Generated by Django 4.0.4 on 2022-05-21 06:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_post_added_on_post_cat_post_updated_on_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='pscat',
            name='likes',
            field=models.ManyToManyField(related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
