# Generated by Django 4.0.5 on 2022-06-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20220606_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=50)),
                ('p_desc', models.TextField()),
                ('p_price', models.IntegerField(max_length=50)),
                ('p_priceupd', models.DateTimeField(auto_now_add=True)),
                ('p_image', models.ImageField(upload_to='pfps')),
            ],
        ),
    ]
